# Generated by Django 6.0.2 on 2026-04-26 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_invoice_amount_invoice_final_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='cgst',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='invoice',
            name='sgst',
            field=models.FloatField(default=0),
        ),
    ]
