# Generated by Django 6.0.2 on 2026-04-26 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_invoice_cgst_invoice_sgst'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='igst',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='invoice',
            name='is_interstate',
            field=models.BooleanField(default=False),
        ),
    ]
