# Generated by Django 6.0.2 on 2026-04-28 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_industry_subscriptionplan_company_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersubscription',
            name='billing_type',
            field=models.CharField(choices=[('monthly', 'Monthly'), ('half_yearly', 'Half Yearly'), ('yearly', 'Yearly')], max_length=20),
        ),
    ]
